#!/bin/bash
# Script para verificar portas em uso no Ubuntu 24.04
echo "=== Verificando Portas em Uso na VPS ==="
echo ""
echo "[Porta 80 (HTTP)]"
sudo lsof -i :80 || echo "Porta 80 está LIVRE"
echo ""
echo "[Porta 443 (HTTPS)]"
sudo lsof -i :443 || echo "Porta 443 está LIVRE"
echo ""
echo "[Porta 3000 (Next.js/App)]"
sudo lsof -i :3000 || echo "Porta 3000 está LIVRE"
echo ""
echo "[Porta 5432 (PostgreSQL)]"
sudo lsof -i :5432 || echo "Porta 5432 está LIVRE"
echo ""
echo "[Porta 6379 (Redis)]"
sudo lsof -i :6379 || echo "Porta 6379 está LIVRE"
echo ""
echo "[Porta 8080 (Evolution API - se aplicável)]"
sudo lsof -i :8080 || echo "Porta 8080 está LIVRE"
echo ""
echo "=== Lista Geral de Portas TCP Abertas (Ouvindo) ==="
sudo ss -tuln | grep LISTEN
